# Generated by Django 5.2.8 on 2025-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='crm_sync_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
